---
dataSize:
  - "4"
  - "16"
  - "64"
  - "256"
  - 1K
  - 4K
  - 16K
  - 128K
  - 1M

messengerTypes:
  - Kafka
  - Nats

payloadSize:
  - "0"
  - "4"
  - "16"
  - "64"
  - "256"
  - 1K
  - 4K
  - 16K
  - 128K
  - 1M
  - 4M
  - 16M
  - 64M

totalMessages:
  - 1M

useReceiver:
  - true
  - false
