---
apiVersion: v1
kind: Namespace
metadata:
  name: __NAMESPACE__
---
apiVersion: v1
kind: Secret
metadata:
  name: object-storage-user-0
  namespace: __NAMESPACE__
immutable: true
type: Opaque
# FIXME: change your own secret!
data:
  CONSOLE_ACCESS_KEY: T0JKSXJaUzNPRnpmSEpWZQ==
  CONSOLE_SECRET_KEY: b3hOVkpibWd4WFpjSGt5NlNrNlF6aTZzUVRxVmRYeEc=
