---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-a
#########################################################
#   Owned Model Storages
#########################################################
---
apiVersion: dash.ulagbulag.io/v1alpha1
kind: ModelStorage
metadata:
  name: tenant-a
  namespace: tenant-a
  labels:
    dash.ulagbulag.io/alias: owned-data-pond
    dash.ulagbulag.io/kind: connected-data-lake
spec:
  objectStorage:
    owned:
      minioConsoleExternalService:
        addressPool: kreonet
        ip: 210.125.84.96
      minioExternalService:
        addressPool: kreonet
        ip: 210.125.84.97
      resources:
        requests:
          storage: 10Ti
      totalNodes: 1
      totalVolumesPerNode: 4
---
apiVersion: dash.ulagbulag.io/v1alpha1
kind: ModelStorageBinding
metadata:
  name: tenant-a
  namespace: tenant-a
  labels:
    dash.ulagbulag.io/alias: owned-data-pond
    dash.ulagbulag.io/kind: connected-data-lake
spec:
  deletionPolicy: Delete
  model: dynamic
  storage:
    owned:
      target: tenant-a
