---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-c
#########################################################
#   Owned Model Storages
#########################################################
---
apiVersion: dash.ulagbulag.io/v1alpha1
kind: ModelStorage
metadata:
  name: tenant-c
  namespace: tenant-c
  labels:
    dash.ulagbulag.io/alias: owned-data-pond
    dash.ulagbulag.io/kind: connected-data-lake
spec:
  objectStorage:
    owned:
      minioConsoleExternalService:
        addressPool: kreonet
        ip: 210.125.84.104
      minioExternalService:
        addressPool: kreonet
        ip: 210.125.84.105
      resources:
        requests:
          storage: 10Ti
      totalNodes: 1
      totalVolumesPerNode: 4
#########################################################
#   Models Storage Bindings - Image
#########################################################
---
apiVersion: dash.ulagbulag.io/v1alpha1
kind: ModelStorageBinding
metadata:
  name: tenant-c-image
  namespace: tenant-c
  labels:
    dash.ulagbulag.io/alias: owned-data-pond
    dash.ulagbulag.io/kind: connected-data-lake
spec:
  deletionPolicy: Delete
  model: image
  storage:
    owned:
      target: tenant-c
#########################################################
#   Models Storage Bindings - Object Detection
#########################################################
---
apiVersion: dash.ulagbulag.io/v1alpha1
kind: ModelStorageBinding
metadata:
  name: tenant-c-object-detection
  namespace: tenant-c
  labels:
    dash.ulagbulag.io/alias: owned-data-pond
    dash.ulagbulag.io/kind: connected-data-lake
spec:
  deletionPolicy: Delete
  model: object-detection
  storage:
    owned:
      target: tenant-c
